### ISSUE TITLE
ActiveModel::ForbiddenAttributes error

### ISSUE THREAD

**Issue by vijikumar55** [rails/strong_parameters#213] opened 2015-01-07 12:27 UTC
Hi,

  I have done the following things. I installed the gem.

1)I created a initializer and added the following line ActiveRecord::Base.send(:include, ActiveModel::ForbiddenAttributesProtection)

2)I removed attr_accessible from model.

Then i  was tried to create a new record, it's was not going to the create method itself. it was giving ActiveModel::ForbiddenAttributes error. Please explain me what could be the problem?

**Comment by fxn** [comment] 2015-01-07 12:31
Hi, this is only for bug reports.

Please make sure you understand the [README](https://github.com/rails/strong_parameters#strong-parameters), and if you have difficulties then maybe ask for help in the [mailing list](https://groups.google.com/forum/#!forum/rubyonrails-talk), IRC, or StackOverflow.

Thanks.

**Comment by vijikumar55** [comment] 2015-01-07 12:32
I am recording bug only.

**Comment by fxn** [comment] 2015-01-07 12:35
If you believe there is a bug in the gem please provide minimal code to reproduce it.

**Comment by vijikumar55** [comment] 2015-01-07 12:41
config/initializers/strong_parameters.rb

ActiveRecord::Base.send(:include, ActiveModel::ForbiddenAttributesProtection)


app/models/role.rb

class Role < ActiveRecord::Base
	#attr_accessible :name, :description
        validates :name, presence: true, uniqueness: { case_sensitive: false}
end


app/controllers/roles_controller.rb

class RolesController < ApplicationController

def create
    @role = Role.new(role_params)
    if @role.save
      redirect_to roles_path, notice: t('Role was successfully created.', default: 'Role was successfully created.')
    else
      render action: "new"
    end
  end

private

def role_params
   params.require(:role).permit(:name,:description)
end

end

**Comment by fxn** [comment] 2015-01-07 12:45
Can you copy & paste verbatim the way you get the exception? (Please use Markdown format for code and keep indentation, see the link at the top-right corner of the comment box.)

**Comment by vijikumar55** [comment] 2015-01-07 12:50
I entered the details(name and description) in the form. after clicking the submit button it's directly throwing ActiveModel::ForbiddenAttributes  error. Please find the attached error message.
![forbidden_error](https://cloud.githubusercontent.com/assets/6594913/5645779/d6ba3a28-9699-11e4-8893-f35bc2c3c13e.png)

**Comment by rafaelfranca** [comment] 2015-01-07 12:53
It seems to be related to can can callback

**Comment by fxn** [comment] 2015-01-07 12:54
The original CanCan gem does not support strong params, please use [cancancan](https://github.com/CanCanCommunity/cancancan) instead.

**Comment by vijikumar55** [comment] 2015-01-07 12:54
ok. Thanks a lot for you help +1

**Comment by fxn** [comment] 2015-01-07 12:58
@vijikumar55 closing in principle then.

**Closed by fxn** 2015-01-07 12:58 UTC
